### ISSUE TITLE
Yummy Search - Failed to parse time string (2019-08-01 00:00:00 00:00:00)

### ISSUE THREAD

**Issue by cnizzardini** [cnizzardini/cakephp-yummy#35]
If a user enters in a time amount, in a field being castToDate, YS fails. Need to check if search value has time, then make a decision was to whether to strictly cast to date or not.

```
[Exception] DateTime::__construct(): Failed to parse time string (2019-08-01 00:00:00 00:00:00) at position 20 (0): Double time specification
#0 /var/www/rootrez/vendor/cnizzardini/cakephp-yummy/src/Service/YummySearch/QueryGenerator.php(57): DateTime->__construct('2019-08-01 00:0...')
#1 /var/www/rootrez/vendor/cnizzardini/cakephp-yummy/src/Service/YummySearch/QueryGenerator.php(28): Yummy\Service\YummySearch\QueryGenerator->getWhere(Object(Cake\ORM\Query), Object(Yummy\Service\YummySearch\Parameter))
#2 /var/www/rootrez/vendor/cnizzardini/cakephp-yummy/src/Controller/Component/YummySearchComponent.php(141): Yummy\Service\YummySearch\QueryGenerator->getQuery(Object(Cake\ORM\Query), '', Object(Yummy\Service\YummySearch\Parameter))
#3 /var/www/rootrez/plugins/Admin/src/Controller/ReservationController.php(178): Yummy\Controller\Component\YummySearchComponent->search(Object(Cake\ORM\Query))
#4 /var/www/rootrez/vendor/cakephp/cakephp/src/Controller/Controller.php(610): Admin\Controller\ReservationController->index()
#5 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(120): Cake\Controller\Controller->invokeAction()
#6 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/ActionDispatcher.php(94): Cake\Http\ActionDispatcher->_invoke(Object(Admin\Controller\ReservationController))
#7 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/BaseApplication.php(235): Cake\Http\ActionDispatcher->dispatch(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Http\BaseApplication->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /var/www/rootrez/vendor/cakephp/cakephp/src/Routing/Middleware/RoutingMiddleware.php(162): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\RoutingMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#11 /var/www/rootrez/vendor/dereuromark/cakephp-setup/src/Middleware/MaintenanceMiddleware.php(47): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#12 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/Runner.php(65): Setup\Middleware\MaintenanceMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#13 /var/www/rootrez/vendor/cakephp/cakephp/src/Routing/Middleware/AssetMiddleware.php(88): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#14 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Routing\Middleware\AssetMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#15 /var/www/rootrez/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(96): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#16 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#17 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#18 /var/www/rootrez/vendor/cakephp/cakephp/src/Http/Server.php(98): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#19 /var/www/rootrez/webroot/index.php(40): Cake\Http\Server->run()
#20 {main}
Request URL: /admin/reservation/?YummySearch%5Bfield%5D%5B%5D=Publisher.name&YummySearch%5Boperator%5D%5B%5D=eq&YummySearch%5Bsearch%5D%5B%5D=StayVancouverHotels.com&YummySearch%5Bfield%5D%5B%5D=Reservation.created&YummySearch%5Boperator%5D%5B%5D=gt_eq&YummySearch%5Bsearch%5D%5B%5D=2019-08-01+00%3A00%3A00+00%3A00%3A00&YummySearch%5Bfield%5D%5B%5D=Reservation.created&YummySearch%5Boperator%5D%5B%5D=lt_eq&YummySearch%5Bsearch%5D%5B%5D=2019-09-09+23%3A59%3A59+23%3A59%3A59

```

**Comment by cnizzardini** [comment]
Created unit test for `castToDate` in next release, but will not solve for this since user submitted an invalid value: `2019-08-01+00:00:00+00:00:00`
